spring.application.name=chat
server.port=${PORT:8090}

spring.datasource.url=${CHAT_DB_URL:jdbc:postgresql://localhost:35432/postgres}
spring.datasource.username=${CHAT_DB_USER:postgres}
spring.datasource.password=${CHAT_DB_PASS:1212}
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}

chat.auction-exchange=${AUCTION_EXCHANGE:auction.exchange}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${OAUTH2_JWK_SET_URI:http://localhost:9191/realms/auctionrealm/protocol/openid-connect/certs}

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
