spring.application.name=auction
server.port=8081
server.shutdown=GRACEFUL

auction.pageSize=12
auction.auction-exchange=auction.exchange
auction.publish-auction-event-job-cron=*/45 * * * * *

management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.application.name}
management.tracing.enabled=false
management.tracing.sampling.probability=1.0

#swagger.api-gateway-url=http://localhost:8989/auction
spring.security.oauth2.resourceserver.jwt.issuer-uri=${OAUTH2_ISSUER_URI:http://localhost:9191/realms/auctionrealm}
eureka.client.service-url.defaultZone:${EUREKA_URL:http://localhost:8761/eureka/}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:15432/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:1212}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:1212}
spring.data.redis.timeout=2000ms
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=4
spring.data.redis.lettuce.pool.min-idle=1

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:1212}

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dvaxnzhso}
cloudinary.api-key=${CLOUDINARY_API_KEY:389657458822817}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:LzUwC4pRQpC89xOUnXSy9k8yDsM}
cloudinary.upload-preset=auction_images
cloudinary.folder=auctions
cloudinary.max-images=5

spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=20

server.tomcat.threads.max=300
server.tomcat.threads.min-spare=50
server.tomcat.accept-count=2000
server.tomcat.max-connections=10000

