name: 'bidding-spring-boot'
services:
  eureka:
    image: reddysai21/bidding-eureka-server
    container_name: eureka
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MANAGEMENT_TRACING_ENABLED=true
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411/api/v2/spans
    ports:
      - "8761:8761"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  api-gateway:
    image: reddysai21/bidding-api-gateway
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - AUCTION_URL=http://host.docker.internal:8081
      - BID_URL=http://host.docker.internal:8085
      - CORS_ALLOWED_ORIGINS=http://localhost:4200
      - OAUTH2_ISSUER_URI=http://keycloak:9191/realms/auctionrealm
      - OAUTH2_JWK_SET_URI=http://keycloak:9191/realms/auctionrealm/protocol/openid-connect/certs
      - EUREKA_URL=http://eureka:8761/eureka
      - MANAGEMENT_TRACING_ENABLED=true
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411/api/v2/spans
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - eureka
    deploy:
      resources:
        limits:
          memory: 700m
    labels:
      logging: "promtail"

  auction:
      image: reddysai21/bidding-auction
      container_name: auction
      environment:
        - SPRING_PROFILES_ACTIVE=docker
        - DB_URL=jdbc:postgresql://auction-db:5432/postgres
        - DB_USERNAME=postgres
        - DB_PASSWORD=1212
        - RABBITMQ_HOST=bidding-rabbitmq
        - RABBITMQ_PORT=5672
        - RABBITMQ_USERNAME=guest
        - RABBITMQ_PASSWORD=1212
        - OAUTH2_ISSUER_URI=http://keycloak:9191/realms/auctionrealm
        - EUREKA_URL=http://eureka:8761/eureka
        - MANAGEMENT_TRACING_ENABLED=true
        - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411/api/v2/spans
      ports:
        - "8081:8081"
      restart: unless-stopped
      depends_on:
        - auction-db
        - bid
        - eureka
      deploy:
        resources:
          limits:
            memory: 1700m
      labels:
        logging: "promtail"

  bid:
      image: reddysai21/bidding-bid
      container_name: bid
      environment:
        - SPRING_PROFILES_ACTIVE=docker
        - DB_URL=jdbc:postgresql://bid-db:5432/postgres
        - DB_USERNAME=postgres
        - DB_PASSWORD=1212
        - RABBITMQ_HOST=bidding-rabbitmq
        - RABBITMQ_PORT=5672
        - RABBITMQ_USERNAME=guest
        - RABBITMQ_PASSWORD=1212
        - OAUTH2_ISSUER_URI=http://keycloak:9191/realms/auctionrealm
        - EUREKA_URL=http://eureka:8761/eureka
        - MANAGEMENT_TRACING_ENABLED=true
        - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411/api/v2/spans
      ports:
        - "8085:8085"
      restart: unless-stopped
      depends_on:
        - bid-db
        - eureka
      deploy:
        resources:
          limits:
            memory: 1700m
      labels:
        logging: "promtail"

  realtime:
      image: reddysai21/bidding-realtime-service
      container_name: realtime-service
      environment:
        - SPRING_PROFILES_ACTIVE=docker
        - RABBITMQ_HOST=bidding-rabbitmq
        - RABBITMQ_PORT=5672
        - RABBITMQ_USERNAME=guest
        - RABBITMQ_PASSWORD=1212
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - OAUTH2_ISSUER_URI=http://keycloak:9191/realms/auctionrealm
        - EUREKA_URL=http://eureka:8761/eureka
        - MANAGEMENT_TRACING_ENABLED=true
        - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411/api/v2/spans
      ports:
        - "8088:8088"
      restart: unless-stopped
      depends_on:
        - redis
        - eureka
      deploy:
        resources:
          limits:
            memory: 1700m
      labels:
        logging: "promtail"

