version: "3.8"
name: "Bidding"
services:
  auction-db:
    image: postgres:15-alpine
    container_name: auction-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1212
      - POSTGRES_DB=postgres
    ports:
      - "15432:5432"
    command:
      - "postgres"
      - "-c"
      - "max_connections=300"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m

  bid-db:
    image: postgres:15-alpine
    container_name: bid-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1212
      - POSTGRES_DB=postgres
    ports:
      - "25432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 500m

  bidding-rabbitmq:
    image: rabbitmq:3.12.11-management
    container_name: bidding-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=1212
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 500m

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    command:
      - start-dev
      - --http-port=9191
      - --features=scripts
      - --import-realm
    container_name: keycloak
    hostname: keycloak
    volumes:
      - ./realm-config:/opt/keycloak/data/import
      - ./spi-jars:/opt/keycloak/providers
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=1212
    ports:
      - "9191:9191"
    deploy:
      resources:
        limits:
          memory: 2gb

  redis:
    image: redis:7-alpine
    container_name: bidding-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 300m